### ISSUE TITLE
cloudflare 无法部署 ， 报错

### ISSUE THREAD

**Issue by Viknopx** [leafmoes/DDG-Chat#3]
Uncaught Error: No such module "node:stream". imported from "worker.js"

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/3e54a309-d440-443d-892f-7bbfdf5f97c1">

**Comment by leafmoes** [comment]
我试了一下，似乎不能通过直接粘贴 /dist/index.js 的文件到 workers ，如果是通过 [方法二](https://github.com/leafmoes/DDG-Chat?tab=readme-ov-file#cloudflare-workers) 则可以成功部署，你可以暂时尝试 第二个 方法

**Comment by leafmoes** [comment]
找到原因了，需要设置 nodejs_compat 标志
![image](https://github.com/user-attachments/assets/284205f9-0296-47d4-a9de-ec5f13762bd0)
