### ISSUE TITLE
添加到 new-api 后，使用 openai 库进行调用时会报错

### ISSUE THREAD

**Issue by axin7** [leafmoes/DDG-Chat#5]
调用代码：
client = OpenAI(
                    api_key=os.getenv("OPENAI_API_KEY"),
                    base_url=os.getenv("OPENAI_BASE_URL"),
                )

                openai_response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[
                        {"role": "system", "content": "..."},
                        {"role": "user", "content": "..."},
                    ],
                    stream=True,
                    temperature=0.8,
                    max_tokens=250,
                )

返回报错：
{'error': {'message': ' (request id: 2024110612082758804413832GMHIjz)', 'type': 'upstream_error', 'param': '500', 'code': 'bad_response_status_code'}}"

使用 vercel、cloudflare、docker 都存在同样报错(baseurl 没问题，没加后缀)

用下面的 curl 方式请求没出现问题：
curl --request POST 'https:// example.com/v1/chat/completions' \
  --header 'Content-Type: application/json' \
  --data '{
    "messages": [
      {
        "role": "user",
        "content": "你好！"
      }
    ],
    "model": "gpt-4o-mini",
    "stream": true
  }'

**Comment by leafmoes** [comment]
不太了解，可能是 newApi 那边的问题？OneApi用户反馈是正常的，我按照你这个代码的逻辑来curl返回也是正常的
```
curl --request POST 'http://localhost:8787/v1/chat/completions' \
  --header 'Content-Type: application/json' \
  --data '{
    "messages": [
      {
        "role": "system",
        "content": "你是一只猫娘，请用猫娘的习惯回答用户的问题"
      },
      {
        "role": "user",
        "content": "你好！"
      }
    ],
    "model": "gpt-4o-mini",
    "stream": true,
    "temperature":0.8,
    "max_tokens":250
  }'
```
![image](https://github.com/user-attachments/assets/c8cefb8a-85ea-4821-ae0d-d1f72e0d28f3)
还有，在ddg-chat里面只有 model，messages，stream三个字段有效，其他字段会被忽略（即使你加了也不会报错，只是程序会无视）

**Comment by leafmoes** [comment]
能否提供一下有关于newApi调用报错的控制台请求？

**Comment by leafmoes** [comment]
猜测可能是newapi会自动给baseurl后面自动加 `/`
导致请求 url 变成 `https:// example.com//v1/chat/completions`

**Comment by axin7** [comment]
刚看了下new-api,没有详细报错信息，只有 500。应该也不是后缀的问题，配置的 baseurl 是：http://example.com,没有加/，其他的好多渠道都这样配置正常的。而且 new-api 后台有个聊天页面，选这个渠道的模型使用就是正常的，用外部的 openai 库调用就报错

**Comment by leafmoes** [comment]
可以使用抓包工具抓一下 new-api 发起的请求嘛？

**Comment by axin7** [comment]
部署在服务器上，抓不到

**Comment by leafmoes** [comment]
应该是newapi的问题，他的上游oneapi都支持。
