### ISSUE TITLE
huggingface如何调用

### ISSUE THREAD

**Issue by hhhaiai** [leafmoes/DDG-Chat#6]
我看很多人已部署成功了，如何调用呢？
https://huggingface.co/spaces/yxmnjxzx/ddg-chat
https://huggingface.co/spaces/leafmoes/ddg-chat
https://huggingface.co/spaces/issaocean/ddg-chat
https://huggingface.co/spaces/iridescentX/duckduck
https://huggingface.co/spaces/drlinzefeng/ddgchat

**Comment by leafmoes** [comment]
请自行搭建项目，使用huggingface分配的域名调用

**Comment by hhhaiai** [comment]
搭建好了  访问域名是： https://yxmnjxzx-ddg-chat.hf.space/

[-](https://huggingface.co/spaces/yxmnjxzx/ddg-chat)  可用


请求无法使用
```
curl --request POST 'https://yxmnjxzx-ddg-chat.hf.space/v1/chat/completions' \
  --header 'Content-Type: application/json' \
  --data '{
    "messages": [
      {
        "role": "user",
        "content": "你好！"
      }
    ],
    "model": "gpt-4o-mini",
    "stream": true
  }'
```

**Comment by hhhaiai** [comment]
不支持吗？

**Comment by leafmoes** [comment]
Hugging Face 官方有限制，v1 开头的调用不了

**Comment by hhhaiai** [comment]
好的，设置环境变量貌似没生效

**Comment by hhhaiai** [comment]
@leafmoes 

https://huggingface.co/spaces/sanbo1200/ddg-chat/blob/main/Dockerfile

看这个配置了，貌似也不行
提示
{"status":401,"error":"Unauthorized: Missing or invalid Authorization header"}

**Comment by leafmoes** [comment]
你在环境变量里设置的 key 你请求的时候没加（？
