### ISSUE TITLE
这个翻译可以使用接口吗

### ISSUE THREAD

**Issue by Wei-Winter** [leafmoes/DDG-Chat#8]
https://github.com/fishjar/kiss-translator
我直接填到这个扩展的OpenAI接口里没有反应，是否还需要按照这个扩展的接口规则在自建呢

**Comment by andyliu91** [comment]
@Wei-Winter 大佬，url和key是怎样设置的

**Comment by andyliu91** [comment]
@Wei-Winter oneapi你试了吗，支持吗
